### ISSUE TITLE
eibc client doesn't recover after hub connection failure

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/eibc-client#60]
quoting @artemijspavlovs 

> appears eibc operator client has trouble reconnecting to the hub if it goes down
Dec 09 00:58:31 ip-10-0-2-55 roller[95592]: {"level":"error","ts":"2024-12-09T00:58:31.051Z","msg":"failed to load LPs","module":"order-resolver","error":"failed to get LP grants: post failed: Post \"[https://rpc-dym-migration-test-2.mzonder.com:443](https://rpc-dym-migration-test-2.mzonder.com/)\": read tcp 10.0.2.55:33056->94.130.32.41:443: read: connection reset by peer"}
Dec 09 09:56:30 ip-10-0-2-55 roller[95592]: {"level":"error","ts":"2024-12-09T09:56:30.987Z","msg":"failed to load LPs","module":"order-resolver","error":"failed to get LP grants: error in json rpc client, with http response metadata: (Status: 502 Bad Gateway, Protocol HTTP/1.1). error unmarshalling: invalid character '<' looking for beginning of value"}
the failed to get LP grants is in the logs since the hub upgrade, after restarting the client it seems to start fine (edited)

**Comment by zale144** [comment]
I don't see an issue here. Once the RPC is up, the eibc-client will continue to fetch LP grants quitely, so you won't see any logs about it.
